name: Android CI - Build APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-apk:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Decode Keystore
        if: secrets.GITHUB_ACTIONS_SIGNING_KEY_BASE64 != ''
        env:
          SIGNING_KEY_BASE64: ${{ secrets.GITHUB_ACTIONS_SIGNING_KEY_BASE64 }}
        run: |
          echo $SIGNING_KEY_BASE64 | base64 --decode > android/app/my-release-key.keystore
          echo "Keystore decoded successfully."

      - name: Create gradle.properties for signing
        if: secrets.GITHUB_ACTIONS_SIGNING_KEY_BASE64 != ''
        run: |
          echo "MYAPP_RELEASE_STORE_FILE=my-release-key.keystore" > android/gradle.properties
          echo "MYAPP_RELEASE_KEY_ALIAS=${{ secrets.GITHUB_ACTIONS_KEY_ALIAS }}" >> android/gradle.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.GITHUB_ACTIONS_STORE_PASSWORD }}" >> android/gradle.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.GITHUB_ACTIONS_KEY_PASSWORD }}" >> android/gradle.properties
          echo "Gradle properties for signing created."
        working-directory: ./

      - name: Give gradlew execution permission
        run: chmod +x android/gradlew
        working-directory: ./

      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: ./android

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RockPaperScissors-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

      - name: Notify if Keystore secret is missing (Optional)
        if: secrets.GITHUB_ACTIONS_SIGNING_KEY_BASE64 == ''
        run: echo "::warning:: Keystore secret (GITHUB_ACTIONS_SIGNING_KEY_BASE64) not found. APK will not be signed or will fail at signing if signing is mandatory."

  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: build-apk
    if: failure() && github.event_name == 'push'
    steps:
      - name: Send Failure Notification (Example)
        run: echo "::error:: Le build de l'APK a échoué pour le commit ${{ github.sha }} sur la branche ${{ github.ref_name }}."
