name: Android CI - Build APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs: # Clé de premier niveau
  build-apk: # Premier job, indenté de 2 espaces
    name: Build Release APK
    runs-on: ubuntu-latest
    steps: # Propriété de build-apk, indentée de 2 espaces par rapport à build-apk (4 au total)
      - name: Checkout repository # Étape, commence par un tiret et est indentée de 2 espaces par rapport à steps (6 au total)
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with: # Propriété de l'étape, indentée de 2 espaces par rapport au tiret (8 au total)
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Decode Keystore
        if: secrets.GITHUB_ACTIONS_SIGNING_KEY_BASE64 != ''
        env:
          SIGNING_KEY_BASE64: ${{ secrets.GITHUB_ACTIONS_SIGNING_KEY_BASE64 }}
        run: |
          echo $SIGNING_KEY_BASE64 | base64 --decode > android/app/my-release-key.keystore
          echo "Keystore decoded successfully."

      - name: Create gradle.properties for signing
        if: secrets.GITHUB_ACTIONS_SIGNING_KEY_BASE64 != ''
        # working-directory: ./ # Commenté car peut-être source d'erreur si non nécessaire explicitement
        run: |
          echo "MYAPP_RELEASE_STORE_FILE=my-release-key.keystore" > android/gradle.properties
          echo "MYAPP_RELEASE_KEY_ALIAS=${{ secrets.GITHUB_ACTIONS_KEY_ALIAS }}" >> android/gradle.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.GITHUB_ACTIONS_STORE_PASSWORD }}" >> android/gradle.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.GITHUB_ACTIONS_KEY_PASSWORD }}" >> android/gradle.properties
          echo "Gradle properties for signing created."

      - name: Give gradlew execution permission
        # working-directory: ./ # Commenté
        run: chmod +x android/gradlew

      - name: Build Release APK
        working-directory: ./android # Nécessaire ici pour exécuter gradlew dans le bon dossier
        run: ./gradlew assembleRelease

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RockPaperScissors-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
